version: '3.9'

services:
  genai-ipe:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: streamlit run streamlit_ui.py --server.port=8501 --server.address=0.0.0.0
